### ISSUE TITLE
不定长中文数据的识别的问题

### ISSUE THREAD

**Issue by AnddyWang** [ayumiymk/aster.pytorch#10]
针对不定长中文识别问题，

可以请教下使用Attention-Based的方法识别的话，
必须使用不定长数据来训练吗？
这个不定长训练该怎么实现呢？
不能像CTC那样，定长训练，不定长识别吗？

非常期待回复，多谢了

**Comment by ayumiymk** [comment]
1. 不是必须使用不定长的数据训练；
2. 中文的长度变化确实比英文大得多，所以不定长训练会好一些。其实代码中也实现了，参考`keep_ratio`这个参数。大致做法是：先将输入图片按照长宽比排序，然后在构建一个batch的时候，选取连续相邻的样本，然后resize成同样的大小。排序的目的是保证一个batch内在resize的时候，形变量不会太大，减小失真。
3. CTC和attention都可以定长训练，不定长识别，不过最好训练和测试统一，不然结果可能不是很好。

**Comment by ws-lin** [comment]
作者您好，我看了代码有关keep_ratio这个参数的片段没有对图片进行排序，是不是在制作数据集为lmdb的时候先排序好了

**Comment by ayumiymk** [comment]
> 作者您好，我看了代码有关keep_ratio这个参数的片段没有对图片进行排序，是不是在制作数据集为lmdb的时候先排序好了

Yes.

**Comment by sssimpleboy** [comment]
> > 作者您好，我看了代码有关keep_ratio这个参数的片段没有对图片进行排序，是不是在制作数据集为lmdb的时候先排序好了
> 
> Yes.

作者您好，我在生成lmdb文件里面没有看到数据排序呀。。。

**Comment by sssimpleboy** [comment]
> > > 作者您好，我看了代码有关keep_ratio这个参数的片段没有对图片进行排序，是不是在制作数据集为lmdb的时候先排序好了
> > 
> > 
> > Yes.
> 
> 作者您好，我在生成lmdb文件里面没有看到数据排序呀。。。

我看到 在读取数据时有对每个batch 内部进行排序。  然后把每个图resize为最大的宽高比 那个大小。 有的图有七八个字，有的图有一个字，把一个字的宽度放成那么大不是有点奇怪嘛。

**Comment by ayumiymk** [comment]
> > > > 作者您好，我看了代码有关keep_ratio这个参数的片段没有对图片进行排序，是不是在制作数据集为lmdb的时候先排序好了
> > > 
> > > 
> > > Yes.
> > 
> > 
> > 作者您好，我在生成lmdb文件里面没有看到数据排序呀。。。
> 
> 我看到 在读取数据时有对每个batch 内部进行排序。 然后把每个图resize为最大的宽高比 那个大小。 有的图有七八个字，有的图有一个字，把一个字的宽度放成那么大不是有点奇怪嘛。

这个有很多方式可以实现了，你可以修改batch_sampler，每个batch只sample长宽比差不多的样本；或者在构建lmdb的时候，就按照长宽比排序，进行有序的构建。
