### ISSUE TITLE
ImportError: cannot import name 'SubsetRandomSampler'

### ISSUE THREAD

**Issue by Igoslow** [ayumiymk/aster.pytorch#12]
when we execute bash scripts/main_test_all.sh, I find this issue that ImportError: cannot import name 'SubsetRandomSampler'. Could you help me?

**Comment by ayumiymk** [comment]
I and most users have not met this question. So it should be an error about your environment. Maybe you can look for help through google.

**Comment by Igoslow** [comment]
Thank you. I have deal with problem when we repair code of line 17 in main.py from torch.utils.data.sampler import SubsetRandomSampler and from torch.utils.data import DataLoader
