### ISSUE TITLE
ValueError: too many values to unpack (expected 3)

### ISSUE THREAD

**Issue by zhijieL387** [ayumiymk/aster.pytorch#13]
~/aster.pytorch/lib/models/model_builder.py in forward(self, input_dict)
     89       return_dict['losses']['loss_rec'] = loss_rec
     90     else:
---> 91       rec_pred, rec_pred_scores = self.decoder.beam_search(encoder_feats, global_args.beam_width, self.eos)
     92       rec_pred_ = self.decoder([encoder_feats, rec_targets, rec_lengths])
     93       loss_rec = self.rec_crit(rec_pred_, rec_targets, rec_lengths)

~/aster.pytorch/lib/models/attention_recognition_head.py in beam_search(self, x, beam_width, eos)
     74 
     75     # https://github.com/IBM/pytorch-seq2seq/blob/fede87655ddce6c94b38886089e05321dc9802af/seq2seq/models/TopKDecoder.py
---> 76     batch_size, l, d = x.size()
     77     # inflated_encoder_feats = _inflate(encoder_feats, beam_width, 0) # ABC --> AABBCC -/-> ABCABC
     78     inflated_encoder_feats = x.unsqueeze(1).permute((1,0,2,3)).repeat((beam_width,1,1,1)).permute((1,0,2,3)).contiguous().view(-1, l, d)

ValueError: too many values to unpack (expected 3)

**Comment by ayumiymk** [comment]
I have not met such a problem but someone else has. I will reopen the related issue. Please refer to #6 to look for help.

**Comment by luoqingyu** [comment]
Do you solve this problem?

**Comment by luoqingyu** [comment]
I have find the reason， parameter  in config.py is different with scripts\stn_att_rec.sh.
Do not   run main.py  directly, run stn_att_rec.sh as readme show。
