### ISSUE TITLE
pretrained model

### ISSUE THREAD

**Issue by lyy-zz** [ayumiymk/aster.pytorch#15]
could you provide a pretrained model?  thank you.

**Comment by ayumiymk** [comment]
The pretrained model is available now. You can download it [here](https://github.com/ayumiymk/aster.pytorch/releases/download/v1.0/demo.pth.tar).

**Comment by kanika02** [comment]
> The pretrained model is available now. You can download it [here](https://github.com/ayumiymk/aster.pytorch/releases/download/v1.0/demo.pth.tar).



Can you provide the (.pth) file of the pretrained model. It will be really helpful for my work. Thanku in advance

**Comment by ayumiymk** [comment]
The given link is just the pretrained model. U can download it and directly load it.
