### ISSUE TITLE
could you provide a pretrained model? thank you.I encountered the following problem when I loaded the downloaded model.

### ISSUE THREAD

**Issue by keliangli** [ayumiymk/aster.pytorch#16]
I encountered the following problem when I loaded the downloaded model.
![1566816723(1)](https://user-images.githubusercontent.com/29944175/63685705-a4c7fa80-c832-11e9-9b83-18c052f96350.png)

**Comment by ayumiymk** [comment]
I have checked the released model, and "tps.inverse_kernel", "tps.padding_matrix" and so on exist in it. So I am not sure what happened.

**Comment by Cabbagehust2507** [comment]
@keliangli Have you fixed that problem? I met the same problem but I haven't fixed it yet. Please tell me if you did it. Thank you so much!
