### ISSUE TITLE
demo.pth.tar error

### ISSUE THREAD

**Issue by DongfeiJi** [ayumiymk/aster.pytorch#23]
tar: This does not look like a tar archive
tar: Skipping to next header
tar: Exiting with failure status due to previous errors
Dear author:
how can i sovle this problem, thanks for answer.

**Comment by ayumiymk** [comment]
Duplicate of #18

**Comment by DongfeiJi** [comment]
what's happened...




------------------ 原始邮件 ------------------
发件人: "Mingkun Yang"<notifications@github.com>; 
发送时间: 2019年10月7日(星期一) 晚上7:51
收件人: "ayumiymk/aster.pytorch"<aster.pytorch@noreply.github.com>; 
抄送: "dongfei"<648513181@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [ayumiymk/aster.pytorch] demo.pth.tar error (#23)




Closed #23.
 
&mdash;

**Comment by ayumiymk** [comment]
The same question has been solved in #18, please refer to it.

**Comment by DongfeiJi** [comment]
Thanks，it helps a lot.



------------------ Original ------------------
