### ISSUE TITLE
Can I adapt the aster for textline recognition?

### ISSUE THREAD

**Issue by pvlinh143bk** [ayumiymk/aster.pytorch#24]
Hi ayumiymk,
I have just came into your aster framework. I'm wondering that it is possible to adapt the framework for textline. If it is possible, what I need to do for adapting.
Could you help me explain the problem?
Thank you very much!
![00000086_l2](https://user-images.githubusercontent.com/54352019/66472006-8ce0c900-eab6-11e9-9478-627f22c34ca7.jpg)

Link textline : https://drive.google.com/file/d/16pSR_zknToN1AwLaKig04NTQxctKfarm/view?usp=sharing

**Comment by ayumiymk** [comment]
Hi, for text line recognition, only increase the width of the input image should be ok.
However, long text images may suffer from 'attention shift'. So some solutions should be proposed to solve the problem.
