### ISSUE TITLE
Reproduced results中L2R的数据是从哪里获得的？代码中的实现应该就是L2R吧

### ISSUE THREAD

**Issue by ironshangki** [ayumiymk/aster.pytorch#26]
那下面的aster.pytorch指的是什么条件下的结果？求解答~~

**Comment by ayumiymk** [comment]
`At present, the bidirectional attention decoder proposed in ASTER is not included in my implementation.`

**Comment by ironshangki** [comment]
感谢你的回答，我知道代码中并没有实现双向decoder。我想问的是readme中的aster.pytorch和ASTER (L2R)有什么区别，既然是同一份code跑的，为啥结果要报告两个。。。没搞明白，求解答

**Comment by ayumiymk** [comment]
ASTER(L2R)是指论文中的结果；
aster.pytorch是指我复现的L2R结果。
两个并不是一份code跑的。

**Comment by ironshangki** [comment]
OK，我了解了，万分感谢
