### ISSUE TITLE
lmdb.Error: /share/zhui/reg_dataset/NIPS2014: No such file or directory

### ISSUE THREAD

**Issue by Cabbagehust2507** [ayumiymk/aster.pytorch#27]
When I clone this project and run it. I had this error, and I haven't known how to fix it now. I hope you can help me with this issue. Thank you so much!
---***----
Traceback (most recent call last):
  File "main.py", line 230, in <module>
    main(args)
  File "main.py", line 127, in main
    args.height, args.width, args.batch_size, args.workers, True, args.keep_ratio)
  File "main.py", line 39, in get_data
    dataset_list.append(LmdbDataset(data_dir_, voc_type, max_len, num_samples))
  File "/home/wanna/Documents/aster.pytorch/lib/datasets/dataset.py", line 53, in __init__
    self.env = lmdb.open(root, max_readers=32, readonly=True)
lmdb.Error: /share/zhui/reg_dataset/NIPS2014: No such file or directory

**Comment by shaohailin** [comment]
@Cabbagehust2507   i have same error .could you tell me how to solve it?

**Comment by Cabbagehust2507** [comment]
@shaohailin you replace this with directory address to your data. example you have 103 put in "./abc/img" and a text file contain labels gt.txt put in". /abc".  So you replace with "./abc". You can try, and feel free to ask me if you meet any troubles. :)

**Comment by shaohailin** [comment]
@Cabbagehust2507 
1.
 i want to know if it is necessary to create the lmdb of  the training set ( synth90k and synthtext ) and the 7 test datasets.
2.
if it is necessary, for example, for test dataset(IIIT5_3000), only choose test data of III5_3000 and lexicon.txt to create .lmdb or choose both train image and test image to create .lmdb?
sorry to bother you!

**Comment by shaohailin** [comment]
![图片](https://user-images.githubusercontent.com/56865153/68862525-8fbf8100-0728-11ea-8f6a-e91938ae4669.png)
there are two .txt files , what should i do to create gt.file
@Cabbagehust2507

**Comment by Cabbagehust2507** [comment]
> @Cabbagehust2507
> 1.
> i want to know if it is necessary to create the lmdb of the training set ( synth90k and synthtext ) and the 7 test datasets.
> 2.
> if it is necessary, for example, for test dataset(IIIT5_3000), only choose test data of III5_3000 and lexicon.txt to create .lmdb or choose both train image and test image to create .lmdb?
> sorry to bother you!
Hi @shaohailin,(1) this source code require dataset need to process into lmdb file.
(2) all train and test datasets need to create lmdb file. But you will create them separately: train_output(.lmdb) and test_output(.lmdb)

**Comment by Cabbagehust2507** [comment]
> ![图片](https://user-images.githubusercontent.com/56865153/68862525-8fbf8100-0728-11ea-8f6a-e91938ae4669.png)
> there are two .txt files , what should i do to create gt.file
> @Cabbagehust2507

I don't use this data. But gt.txt file is the file contains two columns: 1st column contains the image_name, 2nd column contains label of those images.
You can see it clearly in "aster.pytorch/lib/tools/create_svtp_lmdb.py  "

**Comment by shaohailin** [comment]
thanks for your reply!  I have create the gt.txt file of iiit5k dataset according to your introduction about gt.txt file . Then I successfully transform it into lmdb.thank you very much! @Cabbagehust2507

**Comment by Cabbagehust2507** [comment]
@shaohailin You're welcome :)

**Comment by hrx000** [comment]
> When I clone this project and run it. I had this error, and I haven't known how to fix it now. I hope you can help me with this issue. Thank you so much! ---***---- Traceback (most recent call last): File "main.py", line 230, in main(args) File "main.py", line 127, in main args.height, args.width, args.batch_size, args.workers, True, args.keep_ratio) File "main.py", line 39, in get_data dataset_list.append(LmdbDataset(data_dir_, voc_type, max_len, num_samples)) File "/home/wanna/Documents/aster.pytorch/lib/datasets/dataset.py", line 53, in **init** self.env = lmdb.open(root, max_readers=32, readonly=True) lmdb.Error: /share/zhui/reg_dataset/NIPS2014: No such file or directory

Hey cai i am getting this error while training a diffusion model.
![Screenshot (100)](https://user-images.githubusercontent.com/51284717/202651659-43a46ca1-5125-48d2-9910-1d955e3eabb9.png)
where  ./ffhq.lmdb/ffhq/1. png  directory consisting of my dataset. and ffhq is just a folder for storing output.

**Comment by YooWang** [comment]
I thought you can check the path to file.

Rohit Kumar ***@***.***>于2022年11月18日 周五17:06写道：
