### ISSUE TITLE
@ayumiymk 有关lexicon search的问题

### ISSUE THREAD

**Issue by wenston2006** [ayumiymk/aster.pytorch#28]
@ayumiymk 请教一下lexicon search的问题; 我现在的应用是识别发票上的打印文字, 我目前训练了一个文字识别模型,文字识别率在84%; 发票上的文字主要是药品名称和治疗方法名称, 现在我想构建一个词库, 然后采用lexicon search的方法提高文字识别率; 由于发票上的文字经常挨着,而且没有标点符号分隔(比如药品名称左右分别和编号或规格信息挨着), 这样需要自己分词, 分词完后我采用lexicon search的方法来查找词库中匹配的词; 现在的问题是有些发票上识别错的药品名称能够通过lexicon search纠正识别错误, 但也有些识别正确的药品名称会弄错; 我目前所用的lexicon search 方案是调用fuzzywoozy库的extract()函数, 这个函数会计算待查药品名称和词库中的词语之间的edit distance, 并给出一个score;不知道你在采用lexicon search时有没有遇到类似问题?

**Comment by DongfeiJi** [comment]
您好，可以加了联系方式沟通下么？有个地方我没太懂，比如IIIT5K这个数据集，官网只给了一个lexicon.txt，但是很多论文里面都是使用了lexicon50，lexicon1K，请问这个内部是怎么操作的呢？这俩是从lexicon.txt拆分出来的么？如何构建的

**Comment by DongfeiJi** [comment]
> @ayumiymk 请教一下lexicon search的问题; 我现在的应用是识别发票上的打印文字, 我目前训练了一个文字识别模型,文字识别率在84%; 发票上的文字主要是药品名称和治疗方法名称, 现在我想构建一个词库, 然后采用lexicon search的方法提高文字识别率; 由于发票上的文字经常挨着,而且没有标点符号分隔(比如药品名称左右分别和编号或规格信息挨着), 这样需要自己分词, 分词完后我采用lexicon search的方法来查找词库中匹配的词; 现在的问题是有些发票上识别错的药品名称能够通过lexicon search纠正识别错误, 但也有些识别正确的药品名称会弄错; 我目前所用的lexicon search 方案是调用fuzzywoozy库的extract()函数, 这个函数会计算待查药品名称和词库中的词语之间的edit distance, 并给出一个score;不知道你在采用lexicon search时有没有遇到类似问题?

您好，可以加了联系方式沟通下么？有个地方我没太懂，比如IIIT5K这个数据集，官网只给了一个lexicon.txt，但是很多论文里面都是使用了lexicon50，lexicon1K，请问这个内部是怎么操作的呢？这俩是从lexicon.txt拆分出来的么？如何构建的

**Comment by wenston2006** [comment]
@DongfeiJi 我没有用过IIIT5K的数据集,我使用的我这边项目里的数据集.

**Comment by ayumiymk** [comment]
在有字典的时候，我是先使用beam search的方法去得到初步的识别结果，然后再在字典中去找编辑距离最小的作为最终的识别结果。用这种方法的话，如果你能确保你的字典里有正确的识别结果，那么是不可能把正确的识别结果弄错的。

**Comment by wenston2006** [comment]
@ayumiymk  你说的我有些明白了，我之前识别输出的一些药品名在字典里面没有，这可能导致用lexicon　ｓearch出现错误的输出；那如果我的字典不能涵盖所有的药品名，应该如何避免把正确的结果识别错误？

**Comment by ayumiymk** [comment]
你可以借助一下识别的得分。设置一个阈值，识别得分低于阈值的，才使用字典；高于阈值的，就直接使用识别结果。
因为通常识别错误的样本，得分都不是很高。

**Comment by wenston2006** [comment]
@ayumiymk 谢谢回复
