### ISSUE TITLE
Why do we need to scale img_feat to 0.1 in the stn_head?

### ISSUE THREAD

**Issue by sonack** [ayumiymk/aster.pytorch#29]
https://github.com/ayumiymk/aster.pytorch/blob/36e73daf0808dc6e6bcda64ca497b672da959105/lib/models/stn_head.py#L90

Why need to * 0.1 to img_feat? Thanks!

**Comment by ayumiymk** [comment]
I refer to the original implement [here](https://github.com/bgshih/aster/blob/master/core/spatial_transformer.py#L67). The purpose is to make the training more stable.
