### ISSUE TITLE
Training process problems

### ISSUE THREAD

**Issue by Cabbagehust2507** [ayumiymk/aster.pytorch#30]
Hi @ayumiymk ,
I've tested and got the same accuracy like you did. And I've been trying to train model with a small dataset clean that you gave. But I'm not sure about data that I use to train or test is different or not?
It means when I train I will convert dataset (include images and gt.txt files) to .mdb files as you told by tools/create_svtp_lmdb.py. 
But when I want to test, I still need to construct my data to .mdb files, right? or I only need put my images and .txt files?
Thank you so much! I hope you will let me know clearly about this problem.

**Comment by ayumiymk** [comment]
Yes, at present, the code can only be tested with .lmdb file.

**Comment by ayumiymk** [comment]
#31

**Comment by Cabbagehust2507** [comment]
@ayumiymk Thank you so much!
