### ISSUE TITLE
您的代码里面是否包含文字检测定位功能呢？

### ISSUE THREAD

**Issue by Clearlove4396** [ayumiymk/aster.pytorch#33]
尊敬的作者您好，首先非常感谢您开源这么好的代码和模型，我正在使用您的代码和模型做一个关于VQA的研究。但是我发现您的代码好像只能处理截取好的图片，而不能处理完整的图片（比如一张自然场景下的图片，该图片中可能包含多个文本信息）。您有关于相关代码或者模型解决这个问题吗？

**Comment by ayumiymk** [comment]
Yes, this repo can only handle cropped image recognition. Text detection can refer to other works of our [laboratory](http://www.vlrlab.net/).
