### ISSUE TITLE
synthetic_train_data_dir

### ISSUE THREAD

**Issue by shaohailin** [ayumiymk/aster.pytorch#35]
in stn_att_rec.sh
CUDA_VISIBLE_DEVICES=0,1 python main.py \
  --synthetic_train_data_dir /data/mkyang/scene_text/recognition/CVPR2016/ /data/mkyang/scene_text/recognition/NIPS2014/ \
  what's in CVPR2016? and what's in NIPS2014?

**Comment by Cabbagehust2507** [comment]
see #27
