### ISSUE TITLE
自然场景下中文文本识别

### ISSUE THREAD

**Issue by zx123as** [ayumiymk/aster.pytorch#36]
请问自然场景下中文文本识别的数据集可以用于训练这个网络吗？制作数据集、字典的方法与英文一致吗？如果您已有相关的实验数据，可以告知一下识别效果吗？

**Comment by ayumiymk** [comment]
中文当然是可以的。效果也还不错吧，不过没有ctc的好

**Comment by Agiroy4712** [comment]
您好，我在中文数据集上训练，发现第一个epoch精度就70多了，最高，后面就一直没超过了，这是什么问题呢

**Comment by ayumiymk** [comment]
训练数据集是不是太小了？

**Comment by sssimpleboy** [comment]
> 
大佬  请问您是怎么训练的？
我下载的RCTW2017数据 文字只占图片一小部分，一张图中多个文字块，这样的数据是不是不能训练呀？
我在生成mdb文件时，遇到汉字读不进去，看到别人说要进行编码，我也可以编码，但是编完就不知道怎么办了。
还有labelmaps.py  中voc_type 里没有中文的。这样怎么自己弄对应编码格式的list呢？

**Comment by sssimpleboy** [comment]
> 您好，我在中文数据集上训练，发现第一个epoch精度就70多了，最高，后面就一直没超过了，这是什么问题呢

大佬 请问您是怎么训练的？
我下载的RCTW2017数据 文字只占图片一小部分，一张图中多个文字块，这样的数据是不是不能训练呀？
我在生成mdb文件时，遇到汉字读不进去，看到别人说要进行编码，我也可以编码，但是编完就不知道怎么办了。
还有labelmaps.py 中voc_type 里没有中文的。这样怎么自己弄对应编码格式的list呢？

**Comment by sssimpleboy** [comment]
> 您好，我在中文数据集上训练，发现第一个epoch精度就70多了，最高，后面就一直没超过了，这是什么问题呢
您好请问您训练成功了吗？  我训练了半天 ，准确率只有0.005.。。不知道是什么问题。如果有时间的话可以和您交流交流吗？

**Comment by sssimpleboy** [comment]
> 训练数据集是不是太小了？

您好，请问如何准备中英文混合的数据集呢？ 我用TextRecognationDataGenerator 生成了长度为1,2,3,4,5的中文各35W，英文长度为10的图1.5W，图片高度都是64。中文3500个类，英文数字标点供100个类。但是训练出来效果不好。在RCTW2017上准确率才0.
