### ISSUE TITLE
UserWarning: RNN module weights are not part of single contiguous chunk of memory. This means they need to be compacted at every call, possibly greately increasing memory usage. To compact weights again call flatten_parameters().

### ISSUE THREAD

**Issue by shaohailin** [ayumiymk/aster.pytorch#39]
![图片](https://user-images.githubusercontent.com/56865153/68993516-f1602680-08b3-11ea-83f3-fc9f170b8bc3.png)
when i execute bash scripts/stn_att_rec.sh, i have the problem
UserWarning: RNN module weights are not part of single contiguous chunk of memory. This means they need to be compacted at every call, possibly greately increasing memory usage. To compact weights again call flatten_parameters().
could you tell me how to solve it? @ayumiymk

**Comment by ayumiymk** [comment]
This is an issue of Pytorch. Please google it, and you will find the answers.
