### ISSUE TITLE
您好，请教您一些问题

### ISSUE THREAD

**Issue by tzhxs** [ayumiymk/aster.pytorch#40]
我在ocr方面还算是新手，运行了您的代码之后有一些疑问。我发现模型似乎没有办法识别空格(被认为是背景？)，如果想要自动识别并分开两个英文单词应该怎么做呢？使用包含空格的数据集训练吗？

**Comment by ayumiymk** [comment]
这个代码确实无法处理空格，因为训练的时候就没有这样的样本和label，并且字典中也没有空格。
所以要达到你的目的，首先你要有这样的数据，然后就是调整代码中的字典就行。
