### ISSUE TITLE
自制汉字数据集，进行识别，需要需要修改的地方。【肯定句】

### ISSUE THREAD

**Issue by GuoxingYan** [ayumiymk/aster.pytorch#46]
首先非常感谢作者的开源工作，而且issues也是我见过最为友好的。
首先，非常非常重要的就是，在做汉字种类的list的时候一定不要直接汉字上，最好是用encode后的汉字，不然你就需要做下面的功课了。。。。。唉～～

1. lmdb的制作过程博主有说
2. labelmaps中新加入你的数据集的汉字种类。如['一','甲'，......]
3. datasets.py的98行
由    word = self.txn.get(label_key)改成word = self.txn.get(label_key).**decode()。**
   这是因为你的lmdb在制作的时候经过了encode的过程，这个对于英文和数字无所谓，但是对于汉字就必须加入了
4. 在metrics.py中

  if True:
修改成：if  False：
这里做了约束，通过_normalize_text去除掉了**汉字**，如果不做修改会造成评价指标不正常，没有算进去中文。

**Comment by GuoxingYan** [comment]
有个奇怪的是，自己做了虚拟数据，然后训练，之后在真实数据上finetue，这时候学习绿还是设置为1最好，太小不行。0.001就不行了。可能是不太匹配？两个数据

**Comment by whereitogo** [comment]
> 首先非常感谢作者的开源工作，而且issues也是我见过最为友好的。
> 首先，非常非常重要的就是，在做汉字种类的list的时候一定不要直接汉字上，最好是用encode后的汉字，不然你就需要做下面的功课了。。。。。唉～～
> 
> 1. lmdb的制作过程博主有说
> 2. labelmaps中新加入你的数据集的汉字种类。如['一','甲'，......]
> 3. datasets.py的98行
>    由    word = self.txn.get(label_key)改成word = self.txn.get(label_key).**decode()。**
>    这是因为你的lmdb在制作的时候经过了encode的过程，这个对于英文和数字无所谓，但是对于汉字就必须加入了
> 4. 在metrics.py中
> 
> if True:
> 修改成：if False：
> 这里做了约束，通过_normalize_text去除掉了**汉字**，如果不做修改会造成评价指标不正常，没有算进去中文。

关于第二点：labelmaps中新加入你的数据集的汉字种类。如['一','甲'，......]这个不太明白，作者给出的代码中也没有需要对英文字母和数字编码的啊！

**Comment by whereitogo** [comment]
> 有个奇怪的是，自己做了虚拟数据，然后训练，之后在真实数据上finetue，这时候学习绿还是设置为1最好，太小不行。0.001就不行了。可能是不太匹配？两个数据

我的意思是在labelmaps中在哪里添加中文编码？

**Comment by whereitogo** [comment]
> 首先非常感谢作者的开源工作，而且issues也是我见过最为友好的。
> 首先，非常非常重要的就是，在做汉字种类的list的时候一定不要直接汉字上，最好是用encode后的汉字，不然你就需要做下面的功课了。。。。。唉～～
> 
> 1. lmdb的制作过程博主有说
> 2. labelmaps中新加入你的数据集的汉字种类。如['一','甲'，......]
> 3. datasets.py的98行
>    由    word = self.txn.get(label_key)改成word = self.txn.get(label_key).**decode()。**
>    这是因为你的lmdb在制作的时候经过了encode的过程，这个对于英文和数字无所谓，但是对于汉字就必须加入了
> 4. 在metrics.py中
> 
> if True:
> 修改成：if False：
> 这里做了约束，通过_normalize_text去除掉了**汉字**，如果不做修改会造成评价指标不正常，没有算进去中文。

import os
import re
import numpy as np

import inspect

currentdir = os.path.dirname(os.path.abspath(inspect.getfile(inspect.currentframe())))

# 这里的label_dict/icdar_labels.txt文件是我的汉字
def get_dict(path=os.path.join(currentdir, 'label_dict/icdar_labels.txt'), add_space=False, add_eos=False):
    """
    Load text label dict from preprocessed text file.
    Args:
        path: label dict text file path.
        add_space: whether add additional space charater to label dict.
        add_eos: whether add EOS which represents end of sequence to label dict.
    Returns:
        label_dict: text label dict.
    """
    label_dict = dict()
    with open(path, 'r', encoding="utf-8") as f:
        lines = f.readlines()
        for line in lines:
            m = re.match(r'(\d+) (.*)', line)
            idx, label = int(m.group(1)), m.group(2)
            label_dict[idx] = label
        if add_space:
            idx = idx + 1
            label_dict[idx] = ' '
        if add_eos:
            idx = idx + 1
            label_dict[idx] = 'EOS'
    return label_dict


if __name__ == '__main__':
    label_dict = get_dict()
    print(label_dict)
# 上面的汉字标签文件是如下：
0 UNK
1 EOS
2 0
3 1
4 2
5 3
6 4
7 5
8 6
9 7
10 8
11 9
12 a
这样对吗？
然后制作数据集的过程中：
# anno_data文本图像标签
transcripts = [anno['transcription'] for anno in anno_data]
 for char in transcript:
      seq_label.append(self.label_dict[char]) 
是这样吗？

**Comment by sssimpleboy** [comment]
> > 首先非常感谢作者的开源工作，而且issues也是我见过最为友好的。
> > 首先，非常非常重要的就是，在做汉字种类的list的时候一定不要直接汉字上，最好是用encode后的汉字，不然你就需要做下面的功课了。。。。。唉～～
> > 
> > 1. lmdb的制作过程博主有说
> > 2. labelmaps中新加入你的数据集的汉字种类。如['一','甲'，......]
> > 3. datasets.py的98行
> >    由    word = self.txn.get(label_key)改成word = self.txn.get(label_key).**decode()。**
> >    这是因为你的lmdb在制作的时候经过了encode的过程，这个对于英文和数字无所谓，但是对于汉字就必须加入了
> > 4. 在metrics.py中
> > 
> > if True:
> > 修改成：if False：
> > 这里做了约束，通过_normalize_text去除掉了**汉字**，如果不做修改会造成评价指标不正常，没有算进去中文。
> 
> import os import re import numpy as np
> 
> import inspect
> 
> currentdir = os.path.dirname(os.path.abspath(inspect.getfile(inspect.currentframe())))
> 
> # 这里的label_dict/icdar_labels.txt文件是我的汉字
> def get_dict(path=os.path.join(currentdir, 'label_dict/icdar_labels.txt'), add_space=False, add_eos=False): """ Load text label dict from preprocessed text file. Args: path: label dict text file path. add_space: whether add additional space charater to label dict. add_eos: whether add EOS which represents end of sequence to label dict. Returns: label_dict: text label dict. """ label_dict = dict() with open(path, 'r', encoding="utf-8") as f: lines = f.readlines() for line in lines: m = re.match(r'(\d+) (.*)', line) idx, label = int(m.group(1)), m.group(2) label_dict[idx] = label if add_space: idx = idx + 1 label_dict[idx] = ' ' if add_eos: idx = idx + 1 label_dict[idx] = 'EOS' return label_dict
> 
> if **name** == '**main**': label_dict = get_dict() print(label_dict)
> 
> # 上面的汉字标签文件是如下：
> 0 UNK 1 EOS 2 0 3 1 4 2 5 3 6 4 7 5 8 6 9 7 10 8 11 9 12 a 这样对吗？ 然后制作数据集的过程中：
> 
> # anno_data文本图像标签
> transcripts = [anno['transcription'] for anno in anno_data] for char in transcript: seq_label.append(self.label_dict[char]) 是这样吗？

您好，请问您成功训练中文了吗？

**Comment by sssimpleboy** [comment]
> 首先非常感谢作者的开源工作，而且issues也是我见过最为友好的。 首先，非常非常重要的就是，在做汉字种类的list的时候一定不要直接汉字上，最好是用encode后的汉字，不然你就需要做下面的功课了。。。。。唉～～
> 
> 1. lmdb的制作过程博主有说
> 2. labelmaps中新加入你的数据集的汉字种类。如['一','甲'，......]
> 3. datasets.py的98行
>    由    word = self.txn.get(label_key)改成word = self.txn.get(label_key).**decode()。**
>    这是因为你的lmdb在制作的时候经过了encode的过程，这个对于英文和数字无所谓，但是对于汉字就必须加入了
> 4. 在metrics.py中
> 
> if True: 修改成：if False： 这里做了约束，通过_normalize_text去除掉了**汉字**，如果不做修改会造成评价指标不正常，没有算进去中文。
请问您的训练效果如果呢？
