### ISSUE TITLE
CUDA out of memory problem

### ISSUE THREAD

**Issue by Pgwsunny** [ayumiymk/aster.pytorch#47]
CUDA out of memory 
训练模型时遇到以下问题。我想知道作者是否正在将所有数据加载到内存中吗？还有其他解决方法吗？非常感谢你。

![12](https://user-images.githubusercontent.com/52273999/80191132-db674680-8647-11ea-87ae-dbe7af69ea6f.jpg)
![12](https://user-images.githubusercontent.com/52273999/80191274-09e52180-8648-11ea-833f-ef0cbd1b18cd.jpg)

**Comment by ayumiymk** [comment]
Maybe you can reduce the batchsize or use more gpus.
