### ISSUE TITLE
How to improve performance on Chinese dataset

### ISSUE THREAD

**Issue by zhengjiawen** [ayumiymk/aster.pytorch#5]
您好，我尝试将ASTER应用到ICDAR ReCTS数据集上，但是发现对于中文数据集效果比较差。请问对于中文数据集，您有什么建议吗？谢谢。

**Comment by ayumiymk** [comment]
我们也用attention-based methods做过中文识别，不会太差。如果你的结果很差的话，最好看看是不是哪里有问题。

**Comment by ayumiymk** [comment]
因为我觉得这个问题本身和这个仓库无关吧，所以我还是close了吧。如果你发现是因为我的代码有bug，导致中文识别效果不好，我再open。

**Comment by wenston2006** [comment]
我做了如下训练,训练用自己合成的40万条语料图片,测试用了2万图片(从票据上扣出来的);训练数据和验证数据基本不同源;训练了10个epoch,最后验证集上测试精确度为38%;我想问下是否基于注意力机制的算法都存在泛化性能不够强的问题?之前我用github上另一个attention ocr的代码也从头训练过一个模型,训练和验证数据也是不同源, 那个模型泛化性能还要差些.

**Comment by ayumiymk** [comment]
> @ayumiymk 我做了如下训练,训练用自己合成的40万条语料图片,测试用了2万图片(从票据上扣出来的);训练数据和验证数据基本不同源;训练了10个epoch,最后验证集上测试精确度为38%;我想问下是否基于注意力机制的算法都存在泛化性能不够强的问题?之前我用github上另一个attention ocr的代码也从头训练过一个模型,训练和验证数据也是不同源, 那个模型泛化性能还要差些.

你好，这个应该不是attention-decoder模型本身的泛化能力问题，不然你可以用基于ctc的试试。我觉得可能的原因是：
1. 你的合成数据和真实数据的gap有点大；
2. 对于中文识别来说，40w的图片真的太少了；
3. 到目前为止，我在做中文识别，都必须用真实数据finetune，不然效果真的很差；
4. 可以尝试一些domain adaptation的方法

**Comment by wenston2006** [comment]
@ayumiymk 谢谢回复,我还没来得及用你的算法测试不定长中文数据的识别,不知算法对不定长中文数据识别效果如何?我之前训练的基于attention的模型,如果测试数据文字长度和训练数据差别太大,识别效果会很差;如果截取图片,让测试数据文字长度和训练数据一样(比如10个汉字),还能识别出几个汉字来.

**Comment by ayumiymk** [comment]
@wenston2006 看你怎么训练的了。如果使用不定长训练，测试还行。如果定长训练，那么不定长测试的效果确实不行。总之，因为训练数据量的问题，最好还是不定长训练比较靠谱。

**Comment by wenston2006** [comment]
@ayumiymk, 了解了, 谢谢.
