### ISSUE TITLE
训练过程中，占用显存越来越大，直到爆了。

### ISSUE THREAD

**Issue by GuoxingYan** [ayumiymk/aster.pytorch#53]
evaluator.evaluate(test_loader, step=0, tfLogger=eval_tfLogger, dataset=test_dataset)
  File "/home/huawei/yanguoxing/projects/ASTER/lib/evaluators.py", line 81, in evaluate
    images = torch.cat(images)
RuntimeError: CUDA out of memory. Tried to allocate 4.24 GiB (GPU 0; 7.80 GiB total capacity; 4.33 GiB already allocated; 1.60 GiB free; 1013.20 MiB cached

**Comment by GuoxingYan** [comment]
我这个是因为val的数据集太大，导致的，各位 可以试一下

**Comment by sssimpleboy** [comment]
您好，请问您是训练的 CVPR2016的数据吗？
我想训练中文模型，不知道咋弄 = =
