### ISSUE TITLE
How to solve this problem

### ISSUE THREAD

**Issue by waterai12** [ayumiymk/aster.pytorch#6]
File "/home/water/Downloads/aster.pytorch-master/lib/models/attention_recognition_head.py", line 75, in beam_search
    batch_size, l, d = x.size()
ValueError: too many values to unpack (expected 3)

**Comment by zhijieL387** [comment]
@waterai12 Did you solve the problem?

**Comment by Cabbagehust2507** [comment]
Who can solve this problem? I can't fix it. Please tell me if you know how to fix it. Thank you so much!
