### ISSUE TITLE
把训练的输入改成32，100就可以了。改完之后运行一下，再把参数改回来（65，256），发现也可以正常运行。说实话我自己都不知道怎么解决的这个bug

### ISSUE THREAD

**Issue by psuu0001** [ayumiymk/aster.pytorch#68]
> error:
> batch_size, l, d = x.size()
> ValueError: too many values to unpack (expected 3)
> 
> x is the input image.
> 
> when I tried to train the model, the error came up. It seems that the size of input image in lmdb format has one more dimension after encoder. The lmdb input image size after encoder is[ 12, 3, 64, 256]
> However, when I run the demo.py, the input size after encoder is [1, 25, 512], which is acceptable.
> I do not know why there is difference between training and prediction.

请问这个问题你解决了吗？

_Originally posted by @jun214384468 in https://github.com/ayumiymk/aster.pytorch/issues/66#issuecomment-787440632_

**Comment by ASHU-web** [comment]
Is this issue solved? I am also facing the same Issue...

**Comment by lrfighting** [comment]
> > error:
> > batch_size, l, d = x.size()
> > ValueError: too many values to unpack (expected 3)
> > x is the input image.
> > when I tried to train the model, the error came up. It seems that the size of input image in lmdb format has one more dimension after encoder. The lmdb input image size after encoder is[ 12, 3, 64, 256]
> > However, when I run the demo.py, the input size after encoder is [1, 25, 512], which is acceptable.
> > I do not know why there is difference between training and prediction.
> 
> 请问这个问题你解决了吗？
> 
> _Originally posted by @jun214384468 in [#66 (comment)](https://github.com/ayumiymk/aster.pytorch/issues/66#issuecomment-787440632)_

请问您知道如何在测试的输出矫正后的图片
