### ISSUE TITLE
关于测试数据和配置

### ISSUE THREAD

**Issue by yongshuaihuang** [ayumiymk/aster.pytorch#7]
您好，请问可以提供一下你测试用的数据吗？
  --synthetic_train_data_dir /data/mkyang/scene_text/recognition/CVPR2016/ /data/mkyang/scene_text/recognition/NIPS2014/ \
  --test_data_dir /data/mkyang/scene_text/recognition/benchmark_lmdbs_new/IIIT5K_3000/ \

对这三个文件，有什么要求吗？

**Comment by ayumiymk** [comment]
你好，我在tensorflow版本的release中，放过原始数据，参考[这里](https://github.com/bgshih/aster/releases/download/v1.0.2/data_clean.rar)。另外，这三个文件，就是生成的lmdb而已，可以看看[这里](https://github.com/ayumiymk/aster.pytorch#data-preparation)参考如何用原始数据生成lmdb

**Comment by yongshuaihuang** [comment]
非常感谢！祝您生活愉快，工作顺利！

2019-08-02 23:12:50"Mingkun Yang" <notifications@github.com>写道：

你好，我在tensorflow版本的release中，放过原始数据，参考这里。另外，这三个文件，就是生成的lmdb而已，可以看看这里参考如何用原始数据生成lmdb

**Comment by yongshuaihuang** [comment]
此外，您可以给我提供一些中文进行训练，需要更改或者注意的点吗？

**Comment by ayumiymk** [comment]
可以自行下载。比如RCTW2017，LSVT，ReCTS，MTWI等等，这些都包含了大量了中文数据。
