### ISSUE TITLE
How to get character level confidence ??

### ISSUE THREAD

**Issue by KnitVikas** [ayumiymk/aster.pytorch#78]

**Comment by ayumiymk** [comment]
At present, I don't implement this function with beam search. However, if you don't use the beam search while inference, the character-level recognition score can be obtained via [here](https://github.com/ayumiymk/aster.pytorch/blob/master/lib/utils/labelmaps.py#L45).

**Comment by KnitVikas** [comment]
I solved this by picking up the best character probability at each step in beam search.
