### ISSUE TITLE
Special characters not working with pretrained model

### ISSUE THREAD

**Issue by abdullahakmal** [ayumiymk/aster.pytorch#79]
Is it actually the model which is not working with the special characters or have to do something for the model to predict it?

**Comment by ayumiymk** [comment]
For details can be found [here](https://github.com/ayumiymk/aster.pytorch/blob/master/lib/utils/labelmaps.py#L12). If your special characters are out of vocabulary, the pretrained model can't handle. Therefore, you need to re-train a new model with your self-defined vocabulary.

**Comment by abdullahakmal** [comment]
hi,

I tried earlier with all symbols but it didn't detect the basic ones like `-, !, '` I will try to train then.
