### ISSUE TITLE
The dictionary does not support Chinese

### ISSUE THREAD

**Issue by lijun20** [ayumiymk/aster.pytorch#8]
Hi, vocab supports only english, not chinese，what should I do, thank you.

**Comment by ayumiymk** [comment]
Just replace the current vocab.

**Comment by yongshuaihuang** [comment]
@ayumiymk 意思直接在 labelmaps.py 中，将 voc = list("...") 中，替换成中文的list就可以？还是说需要做映射？

**Comment by ayumiymk** [comment]
@yongshuaihuang 直接替换。你可以看到映射是根据voc动态调整的，所以替换voc就行了

**Comment by chensonglu** [comment]
@ayumiymk 您好,我也测试了下中文的识别结果,其中accuracy不会有任何影响,因为用char的id做的,但是在metrics.py中有两个函数(get_str_list和_lexicon_search)用到了_normalize_text,这个应该限定了只有数字和字母,所以在最终显示的时候把中文过滤掉了,导致中文结果显示不出来,但是不影响指标,非常感谢作者的开源工作.

**Comment by sssimpleboy** [comment]
> @ayumiymk 您好,我也测试了下中文的识别结果,其中accuracy不会有任何影响,因为用char的id做的,但是在metrics.py中有两个函数(get_str_list和_lexicon_search)用到了_normalize_text,这个应该限定了只有数字和字母,所以在最终显示的时候把中文过滤掉了,导致中文结果显示不出来,但是不影响指标,非常感谢作者的开源工作.

您好，请问您的中文是先训练，再测试的吗？

**Comment by sssimpleboy** [comment]
> @ayumiymk 您好,我也测试了下中文的识别结果,其中accuracy不会有任何影响,因为用char的id做的,但是在metrics.py中有两个函数(get_str_list和_lexicon_search)用到了_normalize_text,这个应该限定了只有数字和字母,所以在最终显示的时候把中文过滤掉了,导致中文结果显示不出来,但是不影响指标,非常感谢作者的开源工作.


另外，矫正模型与识别模型是分开的两个模型还是一起的一个模型。。

**Comment by sssimpleboy** [comment]
> @ayumiymk 您好,我也测试了下中文的识别结果,其中accuracy不会有任何影响,因为用char的id做的,但是在metrics.py中有两个函数(get_str_list和_lexicon_search)用到了_normalize_text,这个应该限定了只有数字和字母,所以在最终显示的时候把中文过滤掉了,导致中文结果显示不出来,但是不影响指标,非常感谢作者的开源工作.

请问您是怎么训练中文模型的呢？
