### ISSUE TITLE
如何保存矫正后的图片？

### ISSUE THREAD

**Issue by sssimpleboy** [ayumiymk/aster.pytorch#85]
我在model_builder.py中看到了 rectification  相关内容，但是好像没有输出图片的。
我如果想看看矫正后的图片，是不是要将 output['rectified_image'] 乘以标准差再加上均值？

**Comment by YooWang** [comment]
我记得config里面是有一个可以输出校正后图片可视化的参数的， 好像是 vis_dir， 你加入了这个参数，就会在对应的路径有输出， 你看一下 我记得是的。

**Comment by sssimpleboy** [comment]
> 我记得config里面是有一个可以输出校正后图片可视化的参数的， 好像是 vis_dir， 你加入了这个参数，就会在对应的路径有输出， 你看一下 我记得是的。
好的 ，谢谢， 我再试试，
我之前加过一次结果啥都没有，可能是哪里出错了= =

**Comment by sssimpleboy** [comment]
> > 我记得config里面是有一个可以输出校正后图片可视化的参数的， 好像是 vis_dir， 你加入了这个参数，就会在对应的路径有输出， 你看一下 我记得是的。
> > 好的 ，谢谢， 我再试试，
> > 我之前加过一次结果啥都没有，可能是哪里出错了= =



> 我记得config里面是有一个可以输出校正后图片可视化的参数的， 好像是 vis_dir， 你加入了这个参数，就会在对应的路径有输出， 你看一下 我记得是的。
vis_dir 应该是在main.py里有用到，  我运行demo.py 不显示
