### ISSUE TITLE
矫正图像 

### ISSUE THREAD

**Issue by lrfighting** [ayumiymk/aster.pytorch#87]
想请问大家，如何在测试时候得到矫正后的图像？已经进行尝试，但是没有得到结果

**Comment by sssimpleboy** [comment]
> 想请问大家，如何在测试时候得到矫正后的图像？已经进行尝试，但是没有得到结果
将output出来的tensor逆转化一下，再保存为图片

**Comment by lrfighting** [comment]
> > 想请问大家，如何在测试时候得到矫正后的图像？已经进行尝试，但是没有得到结果
> > 将output出来的tensor逆转化一下，再保存为图片

非常感谢
