### ISSUE TITLE
训练集问题

### ISSUE THREAD

**Issue by lrfighting** [ayumiymk/aster.pytorch#88]
请问  训练集  CVPR2016和NIPS2014 是什么数据集？还是说CVPR2016和NIPS2014分别包含了哪些数据集？因为里面打开是已经构造好的数据格式，我无法观察到具体的内容

**Comment by ayumiymk** [comment]
论文里面介绍过，分别对应的是[SynthText (ST)](http://www.robots.ox.ac.uk/~vgg/data/scenetext/) and [MJSynth (MJ)](http://www.robots.ox.ac.uk/~vgg/data/text/)
