### ISSUE TITLE
onnx

### ISSUE THREAD

**Issue by sssimpleboy** [ayumiymk/aster.pytorch#91]
作者您好，请问该模型可以生成 onnx文件吗？  
我试了好种方式都失败了。

**Comment by ayumiymk** [comment]
没了解过，如果你弄好了的话，可以提一个PR

**Comment by sssimpleboy** [comment]
> 没了解过，如果你弄好了的话，可以提一个PR

我之前尝试了一下。失败了，后来把模型分成矫正和识别两部分，矫正的部分转成功了，识别的部分还是失败。只对转换所使用的那张图片有用，对其他图片没用。

**Comment by ayumiymk** [comment]
> > 没了解过，如果你弄好了的话，可以提一个PR
> 
> 我之前尝试了一下。失败了，后来把模型分成矫正和识别两部分，矫正的部分转成功了，识别的部分还是失败。只对转换所使用的那张图片有用，对其他图片没用。

识别部分失败的原因是啥？是因为LSTM吗

**Comment by sssimpleboy** [comment]
> 

这个我也不太清楚。不过我用网上都用的普通CNN+LSTM+CTC的成功了。  现在正在考虑 把aster的attention 换成ctc 试试。因为之前转 dbnet里面有resnet ，也成功了。 所以我猜测是attention部分的原因。

**Comment by sssimpleboy** [comment]
> > 
> 
> 这个我也不太清楚。不过我用网上都用的普通CNN+LSTM+CTC的成功了。 现在正在考虑 把aster的attention 换成ctc 试试。因为之前转 dbnet里面有resnet ，也成功了。 所以我猜测是attention部分的原因。

但是我水平太烂了。 写不出代码。  我现在是把三个部分拆开的。 tps部分还是用aster训练。识别部分是普通的CRNN+CTC  把CNN换成了 resnet。没有一起训练 ，可能两个模型配合的不好。  我把这个弄好了，再考虑把aster的attention改成ctc。
