### ISSUE TITLE
how to predict vertical or 90 degree rotated image

### ISSUE THREAD

**Issue by ramdhan1989** [ayumiymk/aster.pytorch#92]
hi, how to improve prediction for this case :
![vertical_text](https://user-images.githubusercontent.com/41245856/185776125-5c3ba7b9-b7ad-434c-ad41-6295450ba9b6.jpg)
I tried to run the model on this image but the result was not so good (it predicted as "i"). I would like to know if there is a certain mechanism to force the model in recognizing specific character only such as -.,0123456789

thank you

**Comment by ayumiymk** [comment]
In practice, we firstly rotate this image by 90° or -90°. And then select the result with a higher recognition score.
