### ISSUE TITLE
文本矫正后结果

### ISSUE THREAD

**Issue by Floyd809** [ayumiymk/aster.pytorch#96]
请问文本矫正后结果怎么可视化出来?谢谢!

**Comment by wishnotord** [comment]
> 请问文本矫正后结果怎么可视化出来?谢谢!

你好，请问你解决了吗？

**Comment by ayumiymk** [comment]
[      x, _ = self.tps(x, ctrl_points)](https://github.com/ayumiymk/aster.pytorch/blob/master/lib/models/model_builder.py#L77C10-L77C10)
这里的x就是矫正之后的图像，如果要得到正确的RGB图像，还需要对x denormalization一下。
